apiVersion: v1
kind: Service
metadata:
  name: python-mongo-service
spec:
  selector:
    app: python-mongo-pod
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 4500
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-mongo
  labels:
    app: python-mongo-pod
spec:
  selector:
    matchLabels:
      app: python-mongo-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: python-mongo-pod
    spec:
      containers:
      - name: flaskpy3-mongo
        image: docker.io/gpsingh9999/practice-k8s:release-v1
        imagePullPolicy: Always
        env:
        - name: MONGOHOSTNAME
          value: "mongodb"
        - name: FLASKHOSTNAME
          value: "0.0.0.0"
        - name: FLASKPORT
          value: 4500
        - name: MONGOPORT
          value: 27017
        ports:
        - containerPort: 4500
